server:
  tomcat:
    remote-ip-header: x-forward-for
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
    background-processor-delay: 30s
  port: 8088
  servlet:
    context-path: /
spring:
  # 环境 dev|test|prod
  profiles:
    active: @profileActive@
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB
      enabled: true
mybatis-plus:
  # mybatis-plus 的xml路径和实体类包名
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.sxtech.pojo